<?php

define("_WELCOME", "Welcome");
define("_CUSTOMERNUMBER", "Customer Number");
define("_NOTEFILTER", "Note : Use at least one filter for fast search results");
define("_NAME", "Name");
define("_CITY", "City");
define("_POSTALCODE", "Postal Code");
define("_SEARCHTERM", "Search Term");
define("_SUBMIT", "Submit");
define("_CANCEL","Cancel");
define("_SEARCHCUSTOMERS", "Search Customers");
define("_ADDRESNOTFOUND","Address Not Found");
define("_NOMACHESFOUND","No maches found near by");
define("_DIRECTIONS","Directions");
define("_SEARCHNEARBY","Search nearby");
define("_MESSAGE","Message");
define("_HOUSENO","House No");
define("_STREET","Street");
define("_STATE","State");
define("_COUNTRY","Country");
define("_BACK","Back");
define("_SUBMIT","Submit");
define("_SELECTITEM","Select item");
define("_SELECTCOUNTRY","Select Your Country");
define("_SAVECUSTOMIZE","Save Customize");
define("_CUSTOMIZE","Customize");
define("_HISTORY","History");
define("_FAVORITE","Favorite");
define("_HELP","Help");
define("_PROFILE","Profile");
define("_LICENSEINFO","License Info");
define("_SYSTEMS","Systems");
define("_LOGOUT","Logout");
define("_FAVORITELIST","Favorite List");
define("_ADDFAVORITELIST","Add Favorite List");
define("_DESCRIPTION","Description");
define("_REMOVE","Remove");
define("_EDIT","Edit");
define("_Done","Done");
define("_SPECIALCARACTERS","Your string has special characters. \\nThese are not allowed.");
define("_ERRORCONECTIONSAP","There was an error connecting to your SAP System.<br> Please check your Systems Settings, Client, Username and Password or contact us.");
define("_FAVORITESNOTFOUND","Favorites not found");
define("_HISTORYNOTFOUND","History not found");
define("_SAPSYSTEMMESSAGE","SAP System Message");
define("_ERRORMESSAGE","Error Message");
define("_PLEASEPROVIDEUSERID","Please Provide UserId or From and ToDate");
define("_ALERT","Alert");
define("_SHOWMORE","Show More");
define("_NOHEADERNOT","No of Headers Not valid");
define("_SWIPESCROLL","Swip to Scroll");
define("_SALESDOC","Sales organization should not be empty");
define("_LANGUAGE","Language");
define("_SELECTLANGUAGE","Select Your Language");
define("_ENGLISH","English");
define("_SALESORGANIZATION","Sales Organization");
define("_DISTRIBUTIONCHANNEL","Distribution Channel");
define("_DIVISION","Division");
define("_SAVE","Save");
define("_EXPORTALL","Export All");
define("_SENDMAIL","Send as Mail");
define("_TECHNICALNAMES","Technical Names");
define("_EXPORTVIEW","Export View");
define("_SUMNETVALUES","Sum of Netvalues");
define("_MULTISORT","Multi Sort");
define("_EXPORT","Export");
define("_FILTERS","Filters");
define("_FILTER","Filter");
define("_NUMBERCOLUMS","Number of Columns");
define("_SORT","Sort");
define("_ADDNEW","Add New");
define("_DELETE","Delete ");
define("_TABLECOLUMS","Table columns");
define("_CUSTOMERDETAILS","Customer Details");
define("_FROMDATE","From Date");
define("_TODATE","To Date");
define("_NORECORDS","No Records Found");
define("_SOLDPARTY","Sold To Party");
define("_SHIPPARTY","Ship To Party");
define("_SALESPERSON","Sales Person");
define("_SOLDPARTYNAME","Sold To Party Name");
define("_SALESDOCTYPE","Sales Document Type");
define("_VALIDFROMDATE","Valid From Date");
define("_VALIDTODATE","Valid To Date");
define("_HEADERTXT","Header Text");
define("_ITEMS","Items");
define("_ITEM","Item");
define("_DELETEITEM","Delete Item");
define("_ADDITEM","Add Item");
define("_HIGHTITEM","High level item");
define("_FREEGOODS","Free goods");
define("_ORDERQUANTITY","Order Quantity");
define("_SALESPRICE","Sales Price");
define("_PERUNIT","Per Unit");
define("_CURRENCY","Currency");
define("_ITEMTXT","Item Text");
define("_SALESTXT","Sales Text");
define("_PREVIOUS","Previous");
define("_NEXT","Next");
define("_SALESQUOTATION","Sales Quotation");
define("_SENDEMAIL","Send Mail");
define("_SELECTMATERIALFIRST","You Have to Select Material First");
define("_ONEITEMREQUIRED","<b>At least one item is required.</b>");
define("_CREATEDSUCCESS","Created Successfully<br>");
define("_SALESDOCNOTCOMPLETE","The sales document is not yet complete: Edit data ");
define("_PLEASEEDITSALESQUOTATION","Please Edit the sales quotation in SAP GUI and complete the incompletions.");
define("_SALEQUOTATIONNUMBER","Sale Quotation Number");
define("_SALESDOCUMENT","Sales Document");
define("_NETVALUES","Net Values");
define("_COPYSALESQUOTATION","Copy Sales Quotation");
define("_AMOUNT","Amount");
define("_PRICINGUNIT","Pricing unit");
define("_QUOTATIONFROMDATE","Quotation From Date");
define("_QUOTATIONTODATE","Quotation To Date");
define("_NOITEMFOUND","No Items Found");
define("_SALESQUOTATIONNOEXIST","Sales quotation doesn't exist.");
define("_SALESQUOTATIONCHANGE","Sales Quotation Change");
define("_SAPSYSTEMMESSAGECS","Changed Successfully");
define("_DOCUMENTNUMBER","Document Number:");
define("_CREDITCONTROLAREA","Credit Control Area");
define("_SALEORDERNUMBER","Sale Order Number");
define("_CUSTOMERNAME","Customer Name");
define("_CREDITLIMIT","Credit Limit");
define("_UPTO1DAY","Upto 1 Day");
define("_UPTO30DAY","Upto 30 Days");
define("_UPTO60DAY","Upto 60 Days");
define("_UPTO90DAY","Upto 90 Days");
define("_UPTO120DAY","Upto 120 Days");
define("_MORETHEN120DAY","More Then 120 Days");
define("_AGINGINFORMATION","AR Aging Information");
define("_AMOUNTDUE","Amount Due");
define("_KEYDATE","Key Date");
define("_COMPANYCODE","Company Code");
define("_POSTINGDATE","Posting To Date");
define("_OPENITEMS","Open Items");
define("_ALLITEMS","All Items");
define("_REPORTS","Reports");
define("_COMMISSIONREPORT","Commission Report");
define("_BIREPORTS","BI Reports");
define("_SALESORDERREPORT","Sales Order Report");
define("_CUSTOMSCCEHULINGREPORT","Custom Scheduling Report");
define("_ORDERCASH","Order to Cash");
define("_CREATECUSTOMERS","Crear clientes");
define("_EDITCUSTOMERS","Edit Customers");
define("_SEARCHSALESORDERS","Search Sales Orders");
define("_CREATESALESORDER","Create Sales Order");
define("_CREATEDELIVERY","Create Delivery");
define("_DELIVERYLIST","Delivery List");
define("_BILLINGLIST","Billing List");
define("_DASHBOARDSALES","Dashboard: Sales Order Dashboard");
define("_DASHBOARDINVOICED","Dashboard: Invoiced Sales by Region by Customer");
define("_SALESWORKBENCH","Sales Workbench");
define("_PICKINGPOST","Picking And Post Goods Issue");
define("_POSTINCOMINGPAYMENT","Post Incoming Payment");
define("_PORCUREPAY","Procure to Pay");
define("_FINANCECONTROLLING","Finance and Controlling");
define("_LISTSALES","List of Sales Orders with Credit Block");
define("_SALESORDERCREDIT","Sales Order Credit Release");
define("_FORECASTSTOCK","Forecast to Stock");
define("_PRODUCTION","Production");
define("_SALESORDER","Sales Order");
define("_HAVEUPDATESUCCESS","You have updated successfully");
define("_SUCCESSMESSAGE","Success message");
define("_CHANGEPASS","Change Password");
define("_REQUIREDFIELD","Required Field");
define("_ENTEROLDPASS","Enter old password");
define("_ENTERNEWPASS","Enter new password");
define("_CONFIRMPASS","Confirm password");
define("_APPLICATIONSERVER","Application Server");
define("_ROUTERIP","Router IP");
define("_ROUTERPORT","Router Port");
define("_INSTANCENUMBER","Instance Number");
define("_MESAGGESERVER","Message Server");
define("_GROUP","Group");
define("_SYSTEMID","System ID");
define("_BAPIVERSION","bapi version");
define("_LASTNAME","Last Name");
define("_PHONE","Phone");
define("_COMPANYNAME","Company Name");
define("_COMPANYADDRESS","Company Address");
define("_ROLE","Role");
define("_STREETADDRESS","Street Address");
define("_NONE","None");
define("_DOCUMENTBEINGEMAILED","This Document is being emailed upon request by");
define("_PLEASEFINDATTACHMENT","Please find the attachment of");
define("_MAILERERROR","Mailer Error");
define("_MESSAGESENT","Message has been sent");
define("_NOTCONFIGFOLDER","is not Available in Config folder.");
define("_INVALIDOLDPASS","Antigua Contraseña Invalida");
define("_NOSYSTEM","NOSYSTEM");
define("_URLNOTWORKING","URL_NOT_WORKING");
define("_REFRESHPAGE","If you refresh the page, you will see that records will stay just as you modified.");
define("_EXCEPTIONRAISED","Exception raised:");
define("_SALES","Sales");
define("_FINANCE","Finance");
define("_PROCUREMENT","Procurement");
define("_PRODUCTION","Production");
define("_INVENTORY","Inventory");
define("_ZREPORTS","ZReports");
define("_TIME_RECORDING","Time recording");
define("_MASTER_DATA","Master Data");
define("_CHECK_RETURN_STATUS","Check Returns Status -Admin"); 
define("_SELECTSYSTEMTYPE","Select System Type");
define("_CONNECTIONTYPE","Connection type");
define("_SELECTCONNECTIONTYPE","Select the connection type");
define("_CUSTOMPPLICATIONSERVER","Custom Application server");
define("_GROUPSERVERSELECTION","Group/server selection");
define("_EXTENDED","Extended");
define("_SAVECHANGES","Save changes");
define("_BOBJSYSTEMURL","BOBJ System URL");
define("_NOTEPLEASEURLFORMAT","Note: Please give URL with following format:");
define("_CMSNAME","CMS Name");
define("_CMSPORT","CMS Port");
define("_AUTHTYPE","Auth Type");
define("_SELECTAUTHTYPE","Select Auth Type");
define("_NOTEIDCOMPLETED","Note: If SSO setup is completed by deploying BOBJSession web service in your company BOBJ system you can select extended check box above.");
define("_DEMOSYSTEM","Demo System");
define("_COMINGSOON","Coming Soon.........");
define("_GIVEPASSWORDHERE","Given password here will not be saved, it will be used only to validate the system.");
define("_SYSTEMURL","System URL");
define("_DETAILS","Details");
define("_AVAILANLESAPSYSTEM","Available SAP Systems");
define("_ADDNEWSAPSYSTEM","Add New SAP System");
define("_SYSTEMWITH","System with");
define("_ALREADYEXIST","already exist");
define("_PAYMENTTERMS","Payment Terms");
define("_PAYMENTTERMSDESC","Payment Terms Desc.");
DEFINE("_CUSTOMERPO","Customer PO number");

define("_SEARCHSALESQUOTATION","Search Sales Quotation");
define("_CREATESALESQUOTATION","Create Sales Quotation");
define("_DISPLAYSALESQUOTATION","Display/Edit Sales Quotation");
define("_EDITSALESQUOTATIONSOLD","Edit Sales Quotation Sold");
define("_CREATESALESQUOTATIONSOLD","Create Sales Quotation Sold");
define("_SALESORDERDASHBOARD","Sales Dashboard");
define("_SEARCHSALESORDERS","Search Sales Orders");
define("_CREATESALESORDER","Create Sales Order");
define("_DISPLAYSALESORDER","Display Sales Order");
define("_DISPLAYLISTAPPROVE","Display List/Approve");
define("_SALESORDERCREDITBLOCK","Sales Order Credit Block");
define("_DOCUMENTFLOW","Document Flow");
define("_DELIVERYLIST","Delivery List");
define("_CREATEDELIVERY","Create Delivery");
define("_PICKANDPOSTGOODS","Pick And Post Goods");
define("_PICKINGANDPOSTESIGN","Picking And Post Esign");
define("_PRODUCTAVAILABILITYQUOTATION","Product Availability Quotation");
define("_CUSTOMEROPENITEMS","Customer Open Items");
define("_CUSTOMEROPENITEMSHEAD","Customer Open Items Head");
define("_DISPLAYBILLINGDOCUMENT","Display Billing Document");
define("_POSTINCOMINGPAYMENT","Post Incoming Payment");
define("_SEARCHVENDORS","Search Vendors");
define("_DISPLAYANDEDITVENDOR","Display and Edit Vendor");
define("_SUPPLYLIST","Supply List");
define("_SEARCHPURCHASEREQUISITION","Search Purchase Requisition");
define("_CREATEPURCHASEREQUISITION","Create Purchase Requisition");
define("_APPROVECONVERTTOPO","Approve / Convert to PO");
define("_SEARCHPURCHASEORDERS","Search Purchase Orders");
define("_CREATEPURCHASEORDER","Create Purchase Order");
define("_DISPLAYPURCHASEORDER","Display Purchase Order");
define("_APPROVEPURCHASEORDER","Approve Purchase Order");
define("_POSTGOODSRECEIPT","Post Goods Receipt");
define("_PRODUCTAVAILABILITY","Product Availability");
define("_PRODUCTIONWORKBENCH","Production Workbench");
define("_CREATEPRODORDER","Create Prod Order");
define("_RELEASEPRODORDER","Release Prod Order");
define("_CONFIRMPRODORDER","Confirm Prod Order");
define("_PRODUCTIONORDERCOSTING","Production Order Costing");
define("_MATERIALAVAILABILITY","Material Availability");
define("_MATERIALTRANSFER","Material Transfer");
define("_PLACEINSTORAGE","Place In Storage");
define("_TIMERECORDING","Time Recording");
define("_CREATECUSTOMERSMASTER","Create Customers Master");
define("_EDITCUSTOMERMASTER","Edit Customer Master");
define("_APPROVECUSTOMERSMASTER","Approve Customers Master");
define("_REVIEWSTATUSCUSTOMERSMASTER","Review Status Customers Master");
define("_CREATECOSTCENTERMASTER","Create Cost Center Master");
define("_EDITCOSTCENTERMASTER","Edit Cost Center Master");
define("_DISPLAYEDITCUSTOMER","Display and Edit Customer");
define("_BIREPORTS","BI Reports");
define("_CUSTOMERORDERS","Customer Orders");
define("_PLANT","Plant");
define("_MATERIAL","Material");
define("_PAYMENTTERMCODE","Payment Term Code");
define("_PAYMENTTERMDESC","Payment Term");
define("_SU","SU");
define("_CLICKTOCONFIRM", "Click to Confirm");
define("_CUSTOMERPONO", "Customer PO number");
define("_PAYMENTTERMS", "Payment terms");
define("_UOM", "Unit of Measure");
define("_QUOTATIONMAILSUBJECT", "Sales Quotation Document from ThinUI");
define("_QUOTATIONPDFMAIL", "Sales_Quotation_Confirmation_");
define("_SELECTAMATERIAL", "Please select a material first");
define("_SELECTCUSTOMER", "Please select a customer first");
define("_PERCENTAGEDISCOUNT", "Percentage Discount");
define("_SELECTPLANT", "Please select a plant");
define("_ERROR_MANY_COLUMNS", "<script type='text/javascript'>alert('There are too many columns to produce a readable PDF. Please use Excel/CSV download.');</script>");
?>