<?php

define("_WELCOME", "Bienvenido");
define("_CUSTOMERNUMBER", "Número de Cliente");
define("_NOTEFILTER", "Nota: use al menos un filtro para un resultado de búsqueda rápida");
define("_NAME", "Nombre");
define("_CITY", "Ciudad");
define("_POSTALCODE", "Código Postal");
define("_SEARCHTERM", "Término de Búsqueda");
define("_SUBMIT", "Enviar");
define("_CANCEL","Cancelar");
define("_SEARCHCUSTOMERS", "Buscar Cliente");
define("_ADDRESNOTFOUND","Dirección No Encontrada");
define("_NOMACHESFOUND","No se encontraron coincidencias cerca");
define("_DIRECTIONS","Direcciones");
define("_SEARCHNEARBY","Búsqueda cercana");
define("_MESSAGE","Mensaje");
define("_HOUSENO","Número de Casa");
define("_STREET","Calle");
define("_STATE","Estado");
define("_COUNTRY","Pais");
define("_BACK","Atrás");
define("_SUBMIT","Envíar");
define("_SELECTITEM","Seleccionar elemento");
define("_SELECTCOUNTRY","Selecciona Tu Pais");
define("_SAVECUSTOMIZE","Guardar Personalizar");
define("_CUSTOMIZE","Personalizar");
define("_HISTORY","Historia");
define("_FAVORITE","Favorito");
define("_HELP","Ayuda");
define("_PROFILE","Perfil");
define("_LICENSEINFO","Info. de Sistema");
define("_SYSTEMS","Sistemas");
define("_LOGOUT","Cerrar Sesión");
define("_FAVORITELIST","Lista Favorita");
define("_ADDFAVORITELIST","Añadir Lista de Favoritos");
define("_DESCRIPTION","Descripción");
define("_REMOVE","Retirar");
define("_EDIT","Editar");
define("_DONE","Hecho");
define("_SPECIALCARACTERS","Su cadena tiene caracteres especiales. \\nEstos no están permitidos.");
define("_ERRORCONECTIONSAP","Se produjo un error al conectarse a su sistema SAP. <br> Compruebe la configuración de su sistema, el cliente, el nombre de usuario y la contraseña o comuníquese con nosotros.");
define("_FAVORITESNOTFOUND","No se encontraron favoritos");
define("_HISTORYNOTFOUND","Historia no encontrada");
define("_SAPSYSTEMMESSAGE","Mensaje del sistema SAP");
define("_ERRORMESSAGE","Mensaje de error");
define("_PLEASEPROVIDEUSERID","Proporcione UserId o From y ToDate");
define("_ALERT","Alerta");
define("_SHOWMORE","Mostrar Más");
define("_NOHEADERNOT","No de encabezados No es válido");
define("_SWIPESCROLL","Deslizar para desplazarse");
define("_SALESDOC","La organización de ventas no deben estar vacíos");
define("_LANGUAGE","Idioma");
define("_SELECTLANGUAGE","Selecciona Tu idioma");
define("_ENGLISH","Ingles");
define("_SALESORGANIZATION","Organización Ventas");
define("_DISTRIBUTIONCHANNEL","Canal de Distribución");
define("_DIVISION","División");
define("_SAVE","Guardar");
define("_EXPORTALL","Exportar Todo");
define("_SENDMAIL","Enviar como Correo");
define("_TECHNICALNAMES","Nombres Técnicos");
define("_EXPORTVIEW","Vista de Exportación");
define("_SUMNETVALUES","Suma de Valores");
define("_MULTISORT","Ordenación Múltiple");
define("_EXPORT","Exportar");
define("_FILTERS","Filtros");
define("_FILTER","Filtro");
define("_NUMBERCOLUMS","Número de Columnas");
define("_SORT","Ordenar");
define("_ADDNEW","Añadir Nuevo");
define("_DELETE","Eliminar ");
define("_TABLECOLUMS","Columnas de tabla");
define("_CUSTOMERDETAILS","Detalles del cliente");
define("_FROMDATE","De La Fecha");
define("_TODATE","Hasta La Fecha");
define("_NORECORDS","<h3>No se encontrarón archivos</h3>");
define("_SOLDPARTY","Cliente");
define("_SHIPPARTY","Destinatario");
define("_SALESPERSON","Persona de Ventas");
define("_SOLDPARTYNAME","Nombre de Cliente");
define("_SALESDOCTYPE","Tipo Documento de Ventas");
define("_VALIDFROMDATE","Válido Desde Fecha");
define("_VALIDTODATE","Válido Hasta la Fecha");
define("_HEADERTXT","Texto de Cabecera");
define("_ITEMS","Artículos");
define("_ITEM","Artículo");
define("_DELETEITEM","Eliminar Artículo");
define("_ADDITEM","Añadir Artículo");
define("_HIGHTITEM","Artículo de alto nivel");
define("_FREEGOODS","Bienes gratis");
define("_ORDERQUANTITY","Orden la Cantidad");
define("_SALESPRICE","Precio de Venta");
define("_PERUNIT","Por Unidad");
define("_CURRENCY","Moneda");
define("_ITEMTXT","Texto del Artículo");
define("_SALESTXT","Texto de Venta");
define("_PREVIOUS","Anterior");
define("_NEXT","Siguiente");
define("_SALESQUOTATION","Cotización de Venta");
define("_SENDEMAIL","Enviar Correo");
define("_SELECTMATERIALFIRST","Tienes que seleccionar material primero");
define("_ONEITEMREQUIRED","<b> Se requiere al menos un elemento. </b>");
define("_CREATEDSUCCESS","Creado con Éxito <br>");
define("_SALESDOCNOTCOMPLETE","El documento de ventas aún no está completo: Editar datos");
define("_PLEASEEDITSALESQUOTATION","Por favor, edite la oferta de venta en SAP GUI y complete las omisiones");
define("_SALEQUOTATIONNUMBER","Número Cotización Venta");
define("_SALESDOCUMENT","Documento de Venta");
define("_NETVALUES","Valores Netos");
define("_COPYSALESQUOTATION","Copia Cotización de Ventas");
define("_AMOUNT","Cantidad");
define("_PRICINGUNIT","Precio de Unidad");
define("_QUOTATIONFROMDATE","Cotización Desde la Fecha");
define("_QUOTATIONTODATE","Cotización Hasta la Fecha");
define("_NOITEMFOUND","No se encontraron Artículos");
define("_SALESQUOTATIONNOEXIST","La cotización de venta no existe.");
define("_SALESQUOTATIONCHANGE","Cambio de Cotización de Venta");
define("_SAPSYSTEMMESSAGECS","Cambiado con Éxito");
define("_DOCUMENTNUMBER","Número del Documento");
define("_CREDITCONTROLAREA","Área Control Crédito");
define("_SALEORDERNUMBER","Número Orden Venta");
define("_CUSTOMERNAME","Nombre del cliente");
define("_CREDITLIMIT","Limite de Crédito");
define("_UPTO1DAY","Hasta 1 Dia");
define("_UPTO30DAY","Hasta 30 Dias");
define("_UPTO60DAY","Hasta 60 Dias");
define("_UPTO90DAY","Hasta 90 Dias");
define("_UPTO120DAY","Hasta 120 Dias");
define("_MORETHEN120DAY","Más de 120 Dias");
define("_AGINGINFORMATION","Inf. expiración AR");
define("_AMOUNTDUE","Cantidad Debida");
define("_KEYDATE","Fecha Clave");
define("_COMPANYCODE","Codigo de Compañia");
define("_POSTINGDATE","Publicación hasta la fecha");
define("_OPENITEMS","Artículos Abiertos");
define("_ALLITEMS","Todos los Artículos");
define("_REPORTS","Informe");
define("_COMMISSIONREPORT","Informe de la Comision");
define("_BIREPORTS","Informes de BI");
define("_SALESORDERREPORT","Informe de Órdenes de Venta");
define("CUSTOMSCCEHULINGREPORT","Informe de Programación Personalizada");
define("_ORDERCASH","Orden de Cobranza");
define("_CREATECUSTOMERS","Crear Clientes");
define("_EDITCUSTOMERS","Editar Clientes");
define("_SEARCHSALESORDERS","Buscar Órdenes de Venta");
define("_CREATESALESORDER","Crear Orden de Venta");
define("_CREATEDELIVERY","Crear Entrega");
define("_DELIVERYLIST","Lista de Entrega");
define("_BILLINGLIST","Lista de Facturación");
define("_DASHBOARDSALES","Tablero: Tablero de órdenes de venta");
define("_DASHBOARDINVOICED","Tablero: Ventas facturadas por región por cliente");
define("_SALESWORKBENCH","Tablero de Ventas");
define("_PICKINGPOST","Recogida y Salida de Mercancías");
define("_POSTINCOMINGPAYMENT","Envio de Pago Entrante");
define("_PORCUREPAY","Procura Pagar");
define("_FINANCECONTROLLING","Finanza y Control");
define("_LISTSALES","Lista de Órdenes de Venta con Bloqueo de Crédito");
define("_SALESORDERCREDIT","Liberación de Crédito de Orden de Venta");
define("_FORECASTSTOCK","Pronóstico para Stock");
define("_PRODUCTION","Producción");
define("_SALESORDER","Órdenes de Ventas");
define("_HAVEUPDATESUCCESS","Has actualizado exitosamente");
define("_SUCCESSMESSAGE","Mensaje de Éxito");
define("_CHANGEPASS","Cambiar contraseña");
define("_REQUIREDFIELD","Campo Requerido");
define("_ENTEROLDPASS","Introducior contraseña antigua");
define("_ENTERNEWPASS","Introducior nueva contraseña");
define("_CONFIRMPASS","Confirmar contraseña");
define("_APPLICATIONSERVER","Servidor de Aplicaciones");
define("_ROUTERIP","Enrutador IP");
define("_ROUTERPORT","Puerto de Enrutador");
define("_INSTANCENUMBER","Número de Instancia");
define("_MESAGGESERVER","Mensaje de Servidor");
define("_GROUP","Grupo");
define("_SYSTEMID","ID del Sistema");
define("_BAPIVERSION","versión bapi");
define("_LASTNAME","Apellido");
define("_PHONE","Teléfono");
define("_COMPANYNAME","Nombre Compañía");
define("_COMPANYADDRESS","Dirección de Empresa");
define("_ROLE","Rol");
define("_STREETADDRESS","Dirección");
define("_NONE","Ninguna");
define("_DOCUMENTBEINGEMAILED","Este documento está siendo enviado por correo electrónico a petición de");
define("_PLEASEFINDATTACHMENT","Por favor encuentre el adjunto de");
define("_MAILERERROR","Error de Correo");
define("_MESSAGESENT","El mensaje ha sido enviado");
define("_NOTCONFIGFOLDER","no está Disponible en la Carpeta Config.");
define("_INVALIDOLDPASS","Invalid old Password");
define("_NOSYSTEM","NOSYSTEMA");
define("_URLNOTWORKING","URL_NO_FUNCIONA");
define("_REFRESHPAGE","Si actualiza la página, verá que los registros permanecerán tal y como se modificó.");
define("_EXCEPTIONRAISED","Excepción planteada: ");
define("_SALES","Ventas");
define("_FINANCE","Finanzas");
define("_PROCUREMENT","Adquisición");
define("_PRODUCTION","Producción");
define("_INVENTORY","Inventario");
define("_ZREPORTS","Reportes Z");
define("_TIME_RECORDING","Registro de tiempo");
define("_MASTER_DATA","Datos Maestros");
define("_CHECK_RETURN_STATUS","Revisar estatus de devolución-Admin"); 
define("_SELECTSYSTEMTYPE","Seleccione el Tipo de Sistema");
define("_CONNECTIONTYPE","Tipo de conexión");
define("_SELECTCONNECTIONTYPE","Seleccina le tipo de conexión");
define("_CUSTOMPPLICATIONSERVER","Servidor de aplicaciones personalizado");
define("_GROUPSERVERSELECTION","Selección de grupo / servidor");
define("_EXTENDED","Extendido");
define("_SAVECHANGES","Guardar Cambios");
define("_BOBJSYSTEMURL","URL del sistema BOBJ");
define("_NOTEPLEASEURLFORMAT","Nota: Por favor, indique la URL con el siguiente formato:");
define("_CMSNAME","Nombre CMS");
define("_CMSPORT","Puerto CMS");
define("_AUTHTYPE","Tipo de Autenticación");
define("_SELECTAUTHTYPE","Selecciona el tipo de Autenticación");
define("_NOTEIDCOMPLETED","Nota: Si la configuración de SSO se completa al implementar el servicio web BOBJSession en el sistema BOBJ de su empresa, puede seleccionar la casilla de verificación extendida que se encuentra arriba.");
define("_COMINGSOON","Próximamente.........");
define("_DEMOSYSTEM","Sistema Demo");
define("_GIVEPASSWORDHERE","La contraseña dada aquí no se guardará, se usará solo para validar el sistema.");
define("_SYSTEMURL","URL del Sistema");
define("_DETAILS","Detalles");
define("_AVAILANLESAPSYSTEM","Sistemas SAP disponibles");
define("_ADDNEWSAPSYSTEM","Añadir Nuevo Sistema SAP");
define("_SYSTEMWITH","Sistema Con");
define("_ALREADYEXIST","Ya existe");
define("_PAYMENTTERMS","Términos de Pago");
define("_PAYMENTTERMSDESC","Desc. Términos de Pago");
DEFINE("_CUSTOMERPO","Número PO del Cliente");

define("_SEARCHSALESQUOTATION","Buscar cotización de ventas");
define("_CREATESALESQUOTATION","Crear cotización de ventas");
define("_DISPLAYSALESQUOTATION","Mostrar cotización de ventas");
define("_EDITSALESQUOTATIONSOLD","Editar cotización de ventas");
define("_CREATESALESQUOTATIONSOLD","Crear cotización de ventas");
define("_SALESORDERDASHBOARD","Tablero de órdenes de venta");
define("_SEARCHSALESORDERS","Buscar órdenes de Venta");
define("_CREATESALESORDER","Crear órdenes de Venta");
define("_DISPLAYSALESORDER","Mostrar Orden de Venta");
define("_DISPLAYLISTAPPROVE","Mostrar Lista/Aprobar");
define("_SALESORDERCREDITBLOCK","Bloque de Crédito de Orden de Venta");
define("_DOCUMENTFLOW","Flujo de Documento");
define("_DELIVERYLIST","Lista de Entrega");
define("_CREATEDELIVERY","Crear Entrega");
define("_PICKANDPOSTGOODS","Recibir y Registrar Materiales");
define("_PICKINGANDPOSTESIGN","Recibir y Registrar Materiales con Firma Electrónica");
define("_PRODUCTAVAILABILITYQUOTATION","Cotización de Disponibilidad de Producto");
define("_CUSTOMEROPENITEMS","Órdenes Abiertas por Cliente");
define("_CUSTOMEROPENITEMSHEAD","Órdenes Abiertas por Cliente con Encabezado");
define("_DISPLAYBILLINGDOCUMENT","Mostrar Factura");
define("_POSTINCOMINGPAYMENT","Registrar Pago Entrante");
define("_SEARCHVENDORS","Buscar Proveedor");
define("_DISPLAYANDEDITVENDOR","Mostrar y Editar Proveedor");
define("_SUPPLYLIST","Lista de Suministro");
define("_SEARCHPURCHASEREQUISITION","Buscar Requisición de Compra");
define("_CREATEPURCHASEREQUISITION","Crear Requisición de Compra");
define("_APPROVECONVERTTOPO","Aprobar/Convertir a PO");
define("_SEARCHPURCHASEORDERS","Buscar Orden de Compra");
define("_CREATEPURCHASEORDER","Crear Orden de Compra");
define("_DISPLAYPURCHASEORDER","Mostrar Orden de Compra");
define("_APPROVEPURCHASEORDER","Aprobar Orden de Compra");
define("_POSTGOODSRECEIPT","Registrar Recepción de Mercancía");
define("_PRODUCTAVAILABILITY","Disponibilidad de Producto");
define("_PRODUCTIONWORKBENCH","Tablero de Producción");
define("_CREATEPRODORDER","Crear Order de Producción");
define("_RELEASEPRODORDER","Liberar Orden de Producción");
define("_CONFIRMPRODORDER","Confirmar Orden de Producción");
define("_PRODUCTIONORDERCOSTING","Costo de Orden de Producción");
define("_MATERIALAVAILABILITY","Disponibilidad de Material");
define("_MATERIALTRANSFER","Transferencia de Material");
define("_PLACEINSTORAGE","Ingreso a Almacén");
define("_TIMERECORDING","Registro de Tiempo");
define("_CREATECUSTOMERSMASTER","Crear Cliente");
define("_EDITCUSTOMERMASTER","Editar Cliente");
define("_APPROVECUSTOMERSMASTER","Aprobar Cliente");
define("_REVIEWSTATUSCUSTOMERSMASTER","Revisar Estatus de Maestro de Clientes");
define("_CREATECOSTCENTERMASTER","Crear Centro de Costos");
define("_EDITCOSTCENTERMASTER","Editar Centro de Costos");
define("_DISPLAYEDITCUSTOMER","Mostrar/Editar Cliente");
define("_BIREPORTS","Reportes BI");
define("_CUSTOMERORDERS","Órdenes del Cliente");
define("_PLANT","Planta");
define("_MATERIAL","Material");
define("_PAYMENTTERMCODE","Código Plazo de Pago");
define("_PAYMENTTERMDESC","Plazo de Pago");
define("_SU","UV");
define("_CLICKTOCONFIRM", "Click para confirmar");
define("_CUSTOMERPONO", "Orden del cliente");
define("_PAYMENTTERMS", "Términos de Pago");
define("_UOM", "Unidad de Medida");
define("_QUOTATIONMAILSUBJECT", "Documento de Cotización de ThinUI");
define("_QUOTATIONPDFMAIL", "Confirmacion_Cotizacion_");
define("_SELECTAMATERIAL", "Debe de seleccionar un producto");
define("_SELECTCUSTOMER", "Debe seleccionar un cliente");
define("_DISCOUNT", "Descuento");
define("_SELECTPLANT", "Debe seleccionar una planta");
define("_ERROR_MANY_COLUMNS", "<script type='text/javascript'>alert('Hay demasiadas columnas para construir un PDF legible. Por favor use la descarga en Excel/CSV.');</script>");
?>